experiment_config:
  name: null
  savefolder: test_experiment
experiments:
  experiment:
    datasets:
      dataset2:
        generator: LorenzGenerator
        parameters:
          T: 10
          beta: 2.4
          dt: 0.01
          noise_covariance: 0.01
          noise_mean:
          - 0
          - 0
          - 0
          rho: 28
          sigma: 10
          x0:
          - 10
          - 10
          - 10
        sweeps:
          sigma:
            N_steps: 5
            max: 15
            min: 10
        train_test_split:
        - 0.5
        - 0.2
        - 0.3
    kernels:
      k1:
        kernel: GaussianKernel
        parameters:
          bandwidth: 100
      k2:
        kernel: GaussianKernel
        parameters:
          bandwidth: 50
    metrics:
      evaluation:
      - MeanSquaredError
      hyperparameter_tuning: MeanSquaredError
    models:
      model_krr1:
        kernels:
        - k1
        - k1
        - k1
        model: KernelRidgeRegression
        parameters:
          reg: 1.0e-07
      model_krr2:
        kernels:
        - k1
        - k1
        - k2
        model: KernelRidgeRegression
        parameters:
          reg: 1.0e-07
    plots:
      plot1:
        type: scatter
        x: reg
        y:
        - MeanSquaredError
        - k1_bandwidth
      plot2:
        bins: 100
        type: histogram
        x: MeanSquaredError
    reports:
    - MeanSquaredError
